server:
  port: ${PORT:9070} # fallback to 9070 locally

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

  application:
    name: automobile-bavaria-be

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.automobilebavaria.backend: DEBUG

jwt:
  secret: secret-for-my-app-automobile-bavaria-backend-application
  expirationMs: 86400000
