server:
  port: ${SERVER_PORT:9070} # fallback to 9070 locally

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL} # no local fallback
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/master.xml

  application:
    name: automobile-bavaria-be

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    com.automobilebavaria.backend: DEBUG

jwt:
  secret: secret-for-my-app-automobile-bavaria-backend-application
  expirationMs: 86400000
